Make clockd/cogd init script more informative
clockd:
- When there is a failure with the configuration or the manifest, print
  that out and refuse to do anything that would compromise a running
  system (like stop/start when we know start will fail)

both:
- Honor Debian's VERBOSE variable, from /lib/init/vars.sh. Setting
  VERBOSE=yes in /etc/default/rcS brings back the output...

diff --git a/debian/clockwork-agent.cogd.init b/debian/clockwork-agent.cogd.init
--- a/debian/clockwork-agent.cogd.init
+++ b/debian/clockwork-agent.cogd.init
@@ -85,7 +85,7 @@ start)
 	do_start
 	case "$?" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		2)   [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
 stop)
@@ -93,32 +93,32 @@ stop)
 	do_stop
 	case "$?" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		2)   [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
 status)
 	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
 	;;
 reload|force-reload)
-	log_daemon_msg "Reloading $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Reloading $DESC" "$NAME"
 	do_reload
-	log_end_msg $?
+	[ "$VERBOSE" != no ] && log_end_msg $?
 	;;
 restart)
-	log_daemon_msg "Restarting $DESC" "$NAME"
+	[ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$NAME"
 	do_stop
 	case "$?" in
 	0|1)
 		do_start
 		case "$?" in
-		0) log_end_msg 0 ;;
-		1) log_end_msg 1 ;; # Old process is still running
-		*) log_end_msg 1 ;; # Failed to start
+		0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+		1) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Old process is still running
+		*) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Failed to start
 		esac
 		;;
 	*)
 		# Failed to stop
-		log_end_msg 1
+		[ "$VERBOSE" != no ] && log_end_msg 1
 		;;
 	esac
 	;;
diff --git a/debian/clockwork-server.clockd.init b/debian/clockwork-server.clockd.init
--- a/debian/clockwork-server.clockd.init
+++ b/debian/clockwork-server.clockd.init
@@ -26,6 +26,7 @@ SCRIPTNAME=/etc/init.d/clockd
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
+TESTER="$DAEMON $DAEMON_ARGS --test"
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
@@ -39,6 +40,7 @@ do_start() {
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
+	$TESTER >/dev/null || return 2
 	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
 		|| return 1
 	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
@@ -72,8 +74,7 @@ do_stop() {
 }
 
 do_reload() {
-	$DAEMON -t >/dev/null \
-		|| return 1
+	$TESTER >/dev/null || return 1
 	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME \
 		|| return 1
 	return 0
@@ -85,7 +86,7 @@ start)
 	do_start
 	case "$?" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		2)   [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
 stop)
@@ -93,32 +94,38 @@ stop)
 	do_stop
 	case "$?" in
 		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		2)   [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 	esac
 	;;
 status)
 	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
 	;;
 reload|force-reload)
-	log_daemon_msg "Reloading $DESC" "$NAME"
+	[ "$VERBOSE" != "no" ] && log_daemon_msg "Reloading $DESC" "$NAME"
 	do_reload
-	log_end_msg $?
+	[ "$VERBOSE" != "no" ] && log_end_msg $?
 	;;
 restart)
-	log_daemon_msg "Restarting $DESC" "$NAME"
+	[ "$VERBOSE" != "no" ] && log_daemon_msg "Restarting $DESC" "$NAME"
+	$TESTER >/dev/null
+	case "$?" in
+		0) ;;
+		*) [ "$VERBOSE" != "no" ] && log_end_msg 1; exit $?
+	esac
+
 	do_stop
 	case "$?" in
 	0|1)
 		do_start
 		case "$?" in
-		0) log_end_msg 0 ;;
-		1) log_end_msg 1 ;; # Old process is still running
-		*) log_end_msg 1 ;; # Failed to start
+		0) [ "$VERBOSE" != "no" ] && log_end_msg 0 ;;
+		1) [ "$VERBOSE" != "no" ] && log_end_msg 1 ;; # Old process is still running
+		*) [ "$VERBOSE" != "no" ] && log_end_msg 1 ;; # Failed to start
 		esac
 		;;
 	*)
 		# Failed to stop
-		log_end_msg 1
+		[ "$VERBOSE" != "no" ] && log_end_msg 1
 		;;
 	esac
 	;;
